# site settings
title: CCB
subtitle: DIRECTORS
email: josh@jpax.tv
favicon: hatchet.png
description: Film intersects with advertising intersects with brand.
baseurl: "/ccblogn" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: JP- Parkhill
city: New York
state: NY
zip_code: 10001
country: United States of America
lang: en
phone: '917.744.1674'

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  #GitHub: https://github.com/andrewbanchich
  #GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich

  Instagram: https://instagram.com/jptv.media
  LinkedIn: https://www.linkedin.com/in/jptvmedia
  Bluesky: https://bsky.app/profile/parkholer.bsky.social
  Substack: https://jptv.substack.com/
  Website: https://jptv.media

# updated socials for new footer
new_socials:
  Instagram: https://instagram.com/jptv.media
  LinkedIn: https://www.linkedin.com/in/jptvmedia
  Bluesky: https://bsky.app/profile/parkholer.bsky.social
  Substack: https://jptv.substack.com/


# quick links for new footer
quick_links:
  JPTV: https://jptv.media
  Email: mailto:josh@jpax.tv
  917.744.1674: tel:+19177441674


  #- Directors.Work: Directors.Work
  #  url: https://directors.work
  #- title: FilmShit
  #  url: https://filmshit.pro


social_logos:
  https://instagram.com/jptv.media : assets/logos/instagram.svg
  https://www.linkedin.com/in/jptvmedia : assets/logos/linkedin.svg
  https://bsky.app/profile/parkholer.bsky.social : assets/logos/bluesky.svg
  https://jptv.substack.com/ : assets/logos/substack.svg

social_icons:
  - title: Instagram
    url: https://instagram.com
    logo: assets/logos/instagram.svg
  - title: LinkedIn
    url: https://linkedin.com
    logo: assets/logos/linkedin.svg
  - title: Bluesky
    url: https://bluesky.com
    logo: assets/logos/bluesky.svg
  - title: Substack
    url: https://substack.com
    logo: assets/logos/substack.svg





# build settings
markdown: kramdown
permalink: none
comments: false

# sass:
#   style: compressed

sass:
   sass_dir: _sass

   
exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
